/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int inicio = 5;
  /** RegularExpression Id. */
  int defvars = 6;
  /** RegularExpression Id. */
  int procini = 7;
  /** RegularExpression Id. */
  int ASSINGtO = 8;
  /** RegularExpression Id. */
  int MOVE = 9;
  /** RegularExpression Id. */
  int JUMP = 10;
  /** RegularExpression Id. */
  int TURN = 11;
  /** RegularExpression Id. */
  int FACE = 12;
  /** RegularExpression Id. */
  int PUT = 13;
  /** RegularExpression Id. */
  int PICK = 14;
  /** RegularExpression Id. */
  int MOVEtOtHE = 15;
  /** RegularExpression Id. */
  int MOVEiNdIR = 16;
  /** RegularExpression Id. */
  int JUMPtOtHE = 17;
  /** RegularExpression Id. */
  int JUMPiNdIR = 18;
  /** RegularExpression Id. */
  int NOP = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int THEN = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int FACING = 23;
  /** RegularExpression Id. */
  int CANpUT = 24;
  /** RegularExpression Id. */
  int CANpICK = 25;
  /** RegularExpression Id. */
  int CANmOVEiNdIR = 26;
  /** RegularExpression Id. */
  int CANjUMPiNdIR = 27;
  /** RegularExpression Id. */
  int CANmOVEtOtHE = 28;
  /** RegularExpression Id. */
  int CANjUMPtOtHE = 29;
  /** RegularExpression Id. */
  int NOT = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int REPEAT = 33;
  /** RegularExpression Id. */
  int LEFT = 34;
  /** RegularExpression Id. */
  int RIGHT = 35;
  /** RegularExpression Id. */
  int FRONT = 36;
  /** RegularExpression Id. */
  int BACK = 37;
  /** RegularExpression Id. */
  int AROUND = 38;
  /** RegularExpression Id. */
  int NORTH = 39;
  /** RegularExpression Id. */
  int SOUTH = 40;
  /** RegularExpression Id. */
  int EAST = 41;
  /** RegularExpression Id. */
  int WEST = 42;
  /** RegularExpression Id. */
  int BALLOONS = 43;
  /** RegularExpression Id. */
  int CHIPS = 44;
  /** RegularExpression Id. */
  int NUM = 45;
  /** RegularExpression Id. */
  int DIGIT = 46;
  /** RegularExpression Id. */
  int MAY = 47;
  /** RegularExpression Id. */
  int MIN = 48;
  /** RegularExpression Id. */
  int LETRA = 49;
  /** RegularExpression Id. */
  int nombvp = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"assignTo\"",
    "\"move\"",
    "\"jump\"",
    "\"turn\"",
    "\"face\"",
    "\"put\"",
    "\"pick\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMoveInDir\"",
    "\"canJumpInDir\"",
    "\"canMoveToThe\"",
    "\"canJumpToThe\"",
    "\"not\"",
    "\"while\"",
    "\"do\"",
    "\"repeat\"",
    "\"left\"",
    "\"right\"",
    "\"front\"",
    "\"back\"",
    "\"around\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"balloons\"",
    "\"chips\"",
    "<NUM>",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "<LETRA>",
    "<nombvp>",
    "\";\"",
    "\"[\"",
    "\"|\"",
    "\",\"",
    "\"]\"",
    "\"=\"",
    "\":\"",
    "\"\"",
  };

}
